/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class epod_platform_JobScheduler */

#ifndef _Included_epod_platform_JobScheduler
#define _Included_epod_platform_JobScheduler
#ifdef __cplusplus
extern "C" {
#endif
#undef epod_platform_JobScheduler_NO_TIMEOUT
#define epod_platform_JobScheduler_NO_TIMEOUT -1L
/*
 * Class:     epod_platform_JobScheduler
 * Method:    CreateWaitableTimer
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_epod_platform_JobScheduler_CreateWaitableTimer
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     epod_platform_JobScheduler
 * Method:    DestroyWaitableTimer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_epod_platform_JobScheduler_DestroyWaitableTimer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     epod_platform_JobScheduler
 * Method:    SetSuspendState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_epod_platform_JobScheduler_SetSuspendState
  (JNIEnv *, jclass);

/*
 * Class:     epod_platform_JobScheduler
 * Method:    RequestPermissionToSleepIfNotGranted
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_epod_platform_JobScheduler_RequestPermissionToSleepIfNotGranted
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
